events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream backend_app {
        server backend:8000;
    }

    server {
        listen 80;
        server_name www.kadi-store.uz;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name www.kadi-store.uz;

        ssl_certificate /etc/letsencrypt/live/www.kadi-store.uz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.kadi-store.uz/privkey.pem;

        client_max_body_size 20M;

        location /api/ {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /uploads/ {
            alias /usr/share/nginx/html/uploads/;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
